# Generated by Django 3.1.4 on 2021-07-29 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('playerName', models.CharField(default='', max_length=10, primary_key=True, serialize=False)),
                ('teamName', models.CharField(default='', max_length=10)),
                ('gameID', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
